export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",

  PRODUCTS: "/products",
  PRODUCT_DETAIL: "/products/:slug",
  CATEGORIES: "/categories",
  CATEGORY: "/categories/:slug",
  BRANDS: "/brands",
  BRAND: "/brands/:slug",
  SEARCH: "/search",
  FLASH_SALES: "/flash-sales",
  STORE: "/stores/:slug",

  CART: "/cart",
  REQUEST_QUOTE: "/request-quote",

  ACCOUNT: "/account",
  ACCOUNT_PROFILE: "/account/profile",
  ACCOUNT_ORDERS: "/account/orders",
  ACCOUNT_ORDER_DETAIL: "/account/orders/:id",
  ACCOUNT_ADDRESSES: "/account/addresses",
  ACCOUNT_WISHLIST: "/account/wishlist",
  ACCOUNT_REVIEWS: "/account/reviews",
  ACCOUNT_NOTIFICATIONS: "/account/notifications",
  ACCOUNT_SETTINGS: "/account/settings",
  ACCOUNT_RETURNS: "/account/returns",
  ACCOUNT_CHAT: "/account/chat",
  ACCOUNT_WHOLESALE: "/account/wholesale",
} as const;
